### ISSUE TITLE
Bug: v10. Pull to Point throws error and doesn't work.

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-wall-enhancement#13]
If you use the selected tools, drawing walls doesn't work. Disabling "Pull to Point" let's you draw walls again - but you can't really place walls on points anymore.

(Edit: The error occurs if you press shift while moving a point precisely.)

Selected Tools:
![image](https://user-images.githubusercontent.com/44159008/189493067-eac93130-a9a5-4114-a3b5-941e2fe3fd45.png)

Error:
![image](https://user-images.githubusercontent.com/44159008/189493045-800976eb-978a-4d66-a4e0-7d203fb76ebf.png)

**Comment by ironmonk88** [comment]
Is this still an issue in the latest release?

**Comment by tagnullde** [comment]
Hey monk,

I gave it a little wiggle and the error didn't occur. Seems to be fixed.
Thank you.
