### ISSUE TITLE
[BUG] Join Wall Joints

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-wall-enhancement#14]
Nearby points of the selected walls are not being moved to be on the same point. Nothing in the console.

https://user-images.githubusercontent.com/99844555/193964549-faa55441-baa4-4077-a2dd-0d0f02deb417.mp4

Foundry 10.286
D&D 5 2.03
Wall Enhancement 10.1

**Comment by ironmonk88** [comment]
So, technically this is working, it's just that the tolerance for joining points was too low.
Added a setting to allow you to increase the tolerance until it's getting the points you think it should get.
