### ISSUE TITLE
[BUG] Updated converting drawings to walls to use the currently selected wall type.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-wall-enhancement#16]
This feature still only converts them to normal walls. No errors.

https://user-images.githubusercontent.com/99844555/195153383-927c6554-b291-4e40-ad90-7363dff5ec0e.mp4

Forge
Foundry 10.288
Wall Enhancement 10.2
5e 2.0.3
FTC ✔️

**Comment by ironmonk88** [comment]
It's working for me because I have wall types condensed.
Adding this comment here for when I get around to fixing this.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
