### ISSUE TITLE
Feature Request: Button to add walls along the edges of the scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-wall-enhancement#18]
Better Roofs had a button to automatically add walls along the border of the scene's background in v9; for whatever reason this feature got removed. It might be a good addition for Wall Enhancement in the future.

![image](https://user-images.githubusercontent.com/99844555/195900955-704a0b07-d13c-4a43-80a0-45313fc8cf26.png)

**Comment by ironmonk88** [comment]
Should be added to the latest release.
