### ISSUE TITLE
[Feature Request] Configurable Hotkeys

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-wall-enhancement#19]
Would be possible to have configurable hotkeys to quick-swap your currently selected wall drawing type? (A hotkey for walls, a hotkey for terrain, etc)

![image](https://user-images.githubusercontent.com/99844555/197120598-2c4870a0-abfc-49ed-af82-ca85a178c973.png)

**Comment by ironmonk88** [comment]
Should be added to the latest release.
