### ISSUE TITLE
[Request] Continues wall placement

### ISSUE THREAD

**Issue by SirAron111** [ironmonk88/monks-wall-enhancement#23]
**Describe the solution you'd like**
Is it possible to have it so that when I draw a wall, and let go, it immediately starts drawing a new wall from that corner point? So it only stops drawing walls if I kick the other mouse button? DF Architect had that feature, I used it in conjunction to this module back in V10. But these modules have no more support, but that feature made drawing walls so much easier since you never or rarely had to connect the dots manually.

**Comment by ironmonk88** [comment]
Currently... if you hold down the CTRL key while drawing a wall you can continuously draw a wall.
In a previous version I did have the option to change the default drawing style to continuous drawing and holding CTRL to draw a segment.
But Foundry has made that nearly impossible these days without rewriting the code that handles creating the wall.
