### ISSUE TITLE
Optional snap to grid and grid midpoints

### ISSUE THREAD

**Issue by ian612** [ironmonk88/monks-wall-enhancement#27]
**Is your feature request related to a problem? Please describe.**
Many times when I'm adding walls to a pre-made map, the map's walls are laid out with vertices on both grid intersections and grid midpoints. It then becomes frustrating when trying to add walls to the scene in Foundry when I have to constantly switch back and forth between snapping on and off, and when snapping is off I'll often miss the wall vertex slightly and have to go back and clean up the walls. It just adds a lot of time to scene prep.

**Describe the solution you'd like**
If would be nice to have, in the settings, an option to have wall snapping snap to both grid vertices AND midpoints.

**Comment by ironmonk88** [comment]
Fixed in the latest version
