### ISSUE TITLE
[BUG] "Allow One Way Doors" setting is backward

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-wall-enhancement#28]
v11 Foundry, v11.02 of Wall Enhancement

When "Allow One Way Doors" is checked, it disables the ability to have one way doors. Unselecting this option restores the Core behavior of letting one-way doors exist.

My advice is to not change the checkbox, but merely the wording of it. Have it say: "Disable One Way Doors" or something. My rationale for this is that without your module, the default behavior of doors in Foundry Core is to allow one way doors.

**Comment by Crowguard** [comment]
Core Foundry doesn't allow one way doors. 

https://github.com/ironmonk88/monks-wall-enhancement/assets/99844555/90e73e71-bc30-4089-8e87-46c4becac57b

The door is still a door from both directions; it just allows visibility from one side.

**Comment by GambetTV** [comment]
Either I don't understand what you mean, or you're wrong. This is with all modules disabled, one-way door, it prevents vision and movement through the door, but only one side of it. 

https://github.com/ironmonk88/monks-wall-enhancement/assets/72000497/72f59f3b-17a6-4f78-9179-eefc990af6a5

**Comment by Crowguard** [comment]
In both videos, its still a door from both directions. As I already said, the setting makes it so the door is instead a wall from the opposite direction. IE, a one-way door.

**Comment by ironmonk88** [comment]
Closing this as Crowguard is correct, I didn't spend time to read the request fully.
With core, movement is not impeded therefore it is not a one way door, the door still always functions as a door from both sides.  Vision is impaired, but movement is not.
With MWE one way doors, it's a door from one direction and a wall from the other side.  So it's truly a door you can only go through in one direction.
That's the point of the addition, essentially as a trap for players, and the reason it's behind a setting, so you can go back to the core version if you want.
