### ISSUE TITLE
It is possible to drag/resize?

### ISSUE THREAD

**Issue by jacksands** [ironmonk88/monks-wall-enhancement#3]
sometimes I need to resize a map, just to redraw all walls...  is possible to drag resize or any re-scale walls as a group, or all of than?

thank you

**Comment by ironmonk88** [comment]
So I've added another dialog box, after the scene is changed, that will ask if you want Wall Enhancements to update all walls to compensate for the sizing changes in the scene.  This should make it easier than trying to drag and resize all the walls.
