### ISSUE TITLE
[BUG] Alt Right Clicking a door does not lock it silently with this module enabled

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-wall-enhancement#31]
Foundry v11.304 introduced a feature that allows GM's to alt-click a door to open/close/lock/unlock it without triggering the associated sound. With this module engaged, alt-left clicking works fine, but alt-right clicking produces the lock/unlock sound still.

Upon further investigation, it seems associated with the "Toggle Secret Door" setting. If this setting is on, then Alt Right Clicking the door causes the audio to play (and it shouldn't, as Toggle Secret Door claims to only be relevant to Ctrl Right Clicking). If this setting is off, then the door functions as Foundry intended.

**Comment by ironmonk88** [comment]
Fixed in the latest version
