### ISSUE TITLE
Drawing shapes aren't placed and shaped correctly when converted to walls

### ISSUE THREAD

**Issue by Klala** [ironmonk88/monks-wall-enhancement#32]
**Is your feature request related to a problem? Please describe.**
Currently when you use the drawing tools to create squares and circles and convert them to walls they never keep their original size, sometimes they aren't even in the right shape. I noticed this on particularly small shapes. I do a lot of pillars as terrain walls and they are usually small in diameter. Currently, although not working 100% in foundry v11, DF curvy walls does this job way better but with how things are looking, it seems like those modules are abandoned.

**Describe the solution you'd like**
A more precise way to control the walls sizes and shapes.

**Comment by ironmonk88** [comment]
Fixed in the latest version
