### ISSUE TITLE
[BUG] 1-Way Doors, Horizontal

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-wall-enhancement#34]
Door icon still displays for the player if the door is horizontal and the token is next to & underneath the door. 

https://github.com/ironmonk88/monks-wall-enhancement/assets/99844555/6f8f2264-9e2a-476c-8b45-7056607620a2

Door icon is gone as expected when the token is farther away or above the door (with wall direction going the other way).

https://github.com/ironmonk88/monks-wall-enhancement/assets/99844555/7b299162-b147-4ded-b096-4d11517dbfe8

Foundry 11.315
MWE 11.02

**Comment by ironmonk88** [comment]
Fixed in the latest version
