### ISSUE TITLE
[BUG] Module causes lag when previewing measured templates

### ISSUE THREAD

**Issue by jonathanmclaus** [ironmonk88/monks-wall-enhancement#37]
**Describe the bug**
When I hover over a measured template, the squares the template affects or doesn't affect is previewed. When I have this module enabled, if the template intersects walls, the computation of that preview becomes extremely slow and momentarily freezes Foundry.

**To Reproduce**
1. Create a measured circle template.
2. Place some walls intersecting the template.
3. Hover over the template to preview the squares it affects.

**Screenshots**
This is an example of the preview I'm talking about
![image](https://github.com/ironmonk88/monks-wall-enhancement/assets/5731591/68fa0d6a-738b-4236-ae07-4989caa0a4c6)

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version v12
 - System Pathfinder 2e
 - Module version 12.01
 - Not that I saw
 - Yes, used Find the Culprit to narrow it down to this exact module.

**Comment by lancir** [comment]
I'm seeing the same thing - spent a long-time enabling modules one at a time trying to figure out what was causing the lag and came to the same conclusion.  Any chance of getting this looked at?  The module is great, but the lag is a deal breaker.

**Comment by ironmonk88** [comment]
This was an issue with the One Way Door setting.
Tried to make this a bit more efficient.
