### ISSUE TITLE
[BUG] scene freezes with this module enabled

### ISSUE THREAD

**Issue by dharkus5000** [ironmonk88/monks-wall-enhancement#39]
**Describe the bug**
i get this warning in the console after the scene freezes and FF asks me if i want to stop the tab from taking too long
`Script terminated by timeout at:
PIXI.Rectangle.prototype.lineSegmentIntersects@https://voqu-prey-for-death.eu.forge-vtt.com/scripts/foundry.js:49480:58
_testEdgeInclusion@https://voqu-prey-for-death.eu.forge-vtt.com/scripts/foundry.js:51638:18
call_wrapped@https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.12.15.0/lib-wrapper.js:1:37637
init/<@https://assets.forge-vtt.com/bazaar/modules/monks-wall-enhancement/12.01/monks-wall-enhancement.js:221:24
call_wrapper@https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.12.15.0/lib-wrapper.js:1:38850
🎁ClockwiseSweepPolygon.prototype._testEdgeInclusion#0@https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.12.15.0/lib-wrapper.js:1:34099
_identifyEdges@https://voqu-prey-for-death.eu.forge-vtt.com/scripts/foundry.js:51596:17
_testCollision@https://voqu-prey-for-death.eu.forge-vtt.com/scripts/foundry.js:52088:10
testCollision@https://voqu-prey-for-death.eu.forge-vtt.com/scripts/foundry.js:33057:17
getAreaSquares/</square.active<@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:354051
getAreaSquares/<@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:353997
getAreaSquares@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:353957
get squares@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:376572
containsToken@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:376756
notifyActors/auradTokens<@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:377119
filter@https://voqu-prey-for-death.eu.forge-vtt.com/scripts/foundry-esm.js:5010:23
notifyActors@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:377067
checkAuras<@https://voqu-prey-for-death.eu.forge-vtt.com/systems/pf2e/pf2e.mjs:1341:315631
foundry.js:49480:58
`
I don't get the scene freezing for long enough for FF to ask me to stop the tab, if the module is disabled - it happens specifically on only a specific scene in the Prey for Death module, but with find the culprit, i definitely worked out this module was the issue 
the scene freezes after the assets have loaded, for over a minute with this module enabled, and for only like 10s without it enabled, and also freezes when i move or edit the token name on any actor, again it still happens without wall enhancement module enabled, but for a much shorter time, like a few seconds rather than like 30s

**Please complete as much of the following information as possible:**
 - Browser Firefox
 - Foundry Version 12 build 331 (also the previous build, 330?)
 - System [Pathfinder 2e]
 - Module version 12.01

**Comment by ironmonk88** [comment]
Made the function a little more efficient.
