### ISSUE TITLE
Allow configuring the minimum point distance for freehand drawing.

### ISSUE THREAD

**Issue by Varriount** [ironmonk88/monks-wall-enhancement#4]
Currently, it appears that the minimum distance between points placed with the freehand drawing tool is [static](https://github.com/ironmonk88/monks-wall-enhancement/blob/main/monks-wall-enhancement.js#L23). It would be nice to be able to configure this setting, for maps that have fine details.

**Comment by ironmonk88** [comment]
This should be available in the settings now.
