### ISSUE TITLE
[BUG] Players can see all walls on a map when module is active

### ISSUE THREAD

**Issue by AskMP** [ironmonk88/monks-wall-enhancement#42]
**Describe the bug**
Enabling the module in v12 build 331 results in all my players able to see all the walls within any scene. This includes hidden walls, and walls that are not even accessible (exported asset from Dungeon Alchemist)

**Expected behavior**
The outlines / wall types should never be visible to a user.

**Additional context**
To find this out, I deactivated all modules and went through to see what impacted this, once I found the issue with this module, I reactivated everything else, tested, and found everything was as expected. Reactivated this module and it was problematic. Disabled it again and there are no walls for player characters.

**Comment by Crowguard** [comment]
I have not seen this behavior in 12.331; what version of Libwrapper/etc were enabled?

**Comment by AskMP** [comment]
The latest 1.13.2.0 (pulled from both console and the module library)

**Comment by Crowguard** [comment]
Yeah; still cannot replicate that behavior. What system are you using?

**Comment by AskMP** [comment]
DND5E (currently 4.1.0 but it was 2 weeks ago and they do pretty frequent updates)

**Comment by Crowguard** [comment]
Still cannot replicate that as a player on that version.

![image](https://github.com/user-attachments/assets/ee52f562-8214-4688-93b9-13c4231f91a2)

**Comment by AskMP** [comment]
And it figures… I had just loaded the module up to generate screenshots to find that it has resolved. Honest… I had to debug a whack load of modules to decipher which was causing the issue and it was _originally_ this module but it looks like something has updated and is now resolved… I know I posted screenshots somewhere (I think to Foundry’s discord) but it looks like it's no longer there. Would have sworn I generated a video example of it too but I may be crazy.

I appreciate your responses. I really wish (but also grateful there isn't) I had proof of this still not working.

**Comment by AskMP** [comment]
HA! I knew it... I have a video walkthrough as well but will reserve posting that publicly. With the module enabled, players can see the walls in their basic view. When selecting the player token in my GM mode, it shows that they do not. Disabling the module hides all the walls from them.

Module Version v12.01
libWrapper 1.13.2.0

(Other plugins that _may_ have an impact but do not resolve when disabled:
Wall Heigh 6.1.2
Levels 5.3.14

My GM view:
![image](https://github.com/user-attachments/assets/1d732dff-a746-407e-bfa5-6650c3515d79)

My Player View:
![image](https://github.com/user-attachments/assets/65efbf31-4b1d-4825-be85-a99e3d2d86eb)

**Comment by AskMP** [comment]
Disabling _only_ the wall enhancement module results in this:
![image](https://github.com/user-attachments/assets/0a32745c-5ed6-4110-a839-f1c94c29f342)

**Comment by nschoenwald** [comment]
This also happens to me when I have "display walls" enabled as a GM, then log in as a player in the same browser. I don't think my actual players on their machines can see the walls displayed, but it's certainly irritating.

**Comment by ironmonk88** [comment]
I believe this is an issue with how Foundry saves settings.  And I don't think it's actually affecting players.
I've added some code just to double-check though.

**Comment by AskMP** [comment]
Initial testing shows that the new version does seem to correct it. Awesome!
