### ISSUE TITLE
Double click split doesn't work

### ISSUE THREAD

**Issue by BorisMilenski** [ironmonk88/monks-wall-enhancement#7]
As said in the title, double clicking a selected wall segment doesn't split the wall and it throws "Uncaught (in promise) TypeError: wall.update is not a function"
I'm running module version 1.0.5, Foundry Version 9, Build 238, and Pathfinder 2nd Edition 3.0.1.9499. Here's the console log
[localhost-1640374533862.log](https://github.com/ironmonk88/monks-wall-enhancement/files/7775073/localhost-1640374533862.log)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
