### ISSUE TITLE
Door bug seems to duplicate doors that can't be deleted properly. 

### ISSUE THREAD

**Issue by Novabella** [ironmonk88/monks-wall-enhancement#8]
![image](https://user-images.githubusercontent.com/17990493/149682949-d96e0a9b-b9e5-406f-b76e-b25eca03f356.png)
![image](https://user-images.githubusercontent.com/17990493/149682953-170009c7-0bf5-42fe-a6d8-d878958d2f75.png)

A bunch of doors are duplicating themselves weirdly and not deleting right. About half of them bug out. 
![image](https://user-images.githubusercontent.com/17990493/149683023-354b5e55-2a64-40b7-955e-dcd95fa63b58.png)

**Comment by Novabella** [comment]
as soon as I uninstalled the module, all the dup'ed doors disappeared.

**Comment by ironmonk88** [comment]
Is this an issue in the latest version?

**Comment by ironmonk88** [comment]
Closing this as there's been no response an I can't replicate.
