### ISSUE TITLE
Players can see "Convert to walls" option in drawing menu, then see the wall layer when clicking

### ISSUE THREAD

**Issue by psiondragon** [ironmonk88/monks-wall-enhancement#9]
Players can see "Convert to walls" option in drawing menu, then see the wall layer when clicking. 
Not a huge issue, as they don't have permission to change the walls. But the layout of all the walls are seen, even behind fog of war.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
Thank you for catching that.
